### ISSUE TITLE
Add fields for storing curator information

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#119]
This is needed by Klados, and should only include the curator name and ORCID. Looking at some other ontologies, there are a number of ways in which this information is recorded:

- Adding the term editor's URL as a [`dc:contributor`](http://purl.org/dc/elements/1.1/contributor) field (e.g. https://github.com/cmungall in http://purl.obolibrary.org/obo/UBERON_0000020)
- Adding ORCIDs as a `dc:contributor` to the ontology rather than to individual terms [as documented by the Cell Ontology](https://github.com/obophenotype/cell-ontology/blob/5dbdd449268d0945f3c092a2a9fbc4c0a1f8e037/docs/annotation_properties.md), which also proposed using `dc:creator` to record per-term creator information.
- Adding the term editor in the description as an ORCID (e.g. http://purl.obolibrary.org/obo/UBERON_0000020)
  - As far as I can tell this is linked anywhere, but UBERON includes a definition of this ORCID to provide [some more information about C. Mungall](https://github.com/obophenotype/uberon/blob/3b67c11d14ad3871c824e7e7a3029b9fed9c825d/project.owl#L817-L826).
- Adding the term editor using the [IAO:0000117 "term editor" field](http://purl.obolibrary.org/obo/IAO_0000117) (e.g. "Emma Griffiths" in [FOODON:00002584](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http://purl.obolibrary.org/obo/FOODON_00002584), "Alan Ruttenberg" in [IAO:0000409](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/IAO_0000409))
- Adding the definition source using the [IAO:0000119 "definition source"](http://purl.obolibrary.org/obo/IAO_0000119) (e.g. "Barry Smith, Werner Ceusters" in [IAO:0000409](https://www.ebi.ac.uk/ols/ontologies/iao/terms?iri=http://purl.obolibrary.org/obo/IAO_0000409))

I propose we add a `contributors` field as a list of strings to phyloreferences and map it to `dc:contributor` in JSON-LD. We would recommend that contributors should be recorded as a string in the format `Name (orcid:1111-2222-3333-4444)`.

**Comment by hlapp** [comment]
@matentzn or @cmungall if either of you have any additional pointers or comments on where to look for ontology term curator attribution recommended practices for OBO, that'd be useful.

(FYI, in the OG issue documentation above, a _phyloreference_ becomes a (defined) class in an ontology, so it's about documenting curators at the level of terms/classes.)

**Comment by matentzn** [comment]
Here is a nice issue that illustrates the chaos: https://github.com/information-artifact-ontology/ontology-metadata/issues/60

If you cover all properties mentioned by this thread you are probably in a good place.

We are pushing hard (against plenty resistance) to standardise on `dcterms:contributor orcid:123`, but its a slow process. 

dc:creator is found as well, always check the dcterms vs dc elements variants of IRIs if you want everything.

My two cents: `dcterms:contributor` plus orcid/ror/wikidata is the right way to go.

**Comment by gaurav** [comment]
@balhoff pointed out that Dublin Core recommends that [creators and contributors are identified by URI if feasible](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/creator), and suggested the following approach:

```turtle
:phyloref0 dc:contributor <http://orcid.org/0000-0003-0587-0454> .
<http://orcid.org/0000-0003-0587-0454> foaf:name "Gaurav Vaidya"
```

This can be [represented in JSON-LD](https://tinyurl.com/2lmahvcl) in a pretty compact way by adding two additional terms to our JSON-LD context:

```json
{
  "@context": {
    "contributors": {
      "@id": "http://purl.org/dc/terms/contributor",
      "@container": "@set"
    },
    "name": "http://xmlns.com/foaf/0.1/name"
  },

  "contributors": [{
    "@id": "http://orcid.org/0000-0003-0587-0454",
    "name": "Gaurav Vaidya"
  }, {
    "@id": "https://orcid.org/0000-0001-9107-0714",
    "name": "Hilmar Lapp"
  }]
}
```

A contributor without an ORCID could either be represented by a blank node with a `foaf:name` property (i.e. `"contributors": [{ "name": "Albert Einstein" }]`) or by just including their directly in the `contributors` list (i.e. `"contributors": [ "Albert Einstein" ]`).

**Comment by hlapp** [comment]
Sounds like a good plan to me, and I agree, the `dcterms` namespace properties should have a URI or object as value.
