### ISSUE TITLE
No longer consider empty phylogenies to be errors

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#13]
We currently consider empty phylogenies in Newick strings to be errors:
https://github.com/phyloref/phyx.js/blob/d3477876d1f89045aee1276caae208055e26598c/test/phylogenies.js#L44-L57

This should not be the case, as this is a valid phylogeny!

**Comment by hlapp** [comment]
Perhaps so, but how is an empty phylogeny useful for either resolving a phyloreference on, or for using as a reference phylogeny?

**Comment by gaurav** [comment]
Decision: if a phylogeny is "defined" but it is not actually set, that is an error case.
