### ISSUE TITLE
SpecimenWrapper label defaults to `urn:catalog::` if occurrence ID is empty

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#145]
If you create a SpecimenWrapper from a blank occurrence ID, the returned occurrence ID is `urn:catalog:::`. This is because the current code constructs a 

```
const wrapped = SpecimenWrapper.fromOccurrenceID('');
print(wrapper.label);
# Returns "Specimen urn:catalog:::"
```

This is because:
- The getter method for `occurrenceID` attempts to construct a Darwin Core triple from the relevant fields, but these are empty.
- Our default label is `Specimen {occurrenceID}`

We should change this such that:
- [x] It's probably not useful to have an occurrence ID with a `urn:catalog:::` prefix -- we should only return the raw occurrence ID.
- [x] We should have the label default to `Specimen {occurrenceID}`, but only if occurrenceID is not blank.
- [x] <s>Should we include the basisOfRecord in the label as well?</s> This would just bake additional information into the label.

**Comment by hlapp** [comment]
> * Should we include the basisOfRecord in the label as well?

Would that help reduce potential ambiguity, or just bake additional information into the label? I'd be in favor of the former, but don't think the latter needs to our should be a goal.
