### ISSUE TITLE
Allow the base URI to be changed on PhyxWrapper

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#27]
Currently, the base URI of a Phyx file is hardcoded: https://github.com/phyloref/phyx.js/blob/9bbb5a7e4df3cf719b3382902067a20fbe3f4f84/src/wrappers/PhyxWrapper.js#L29-L32

As is the JSON context: https://github.com/phyloref/phyx.js/blob/9bbb5a7e4df3cf719b3382902067a20fbe3f4f84/src/wrappers/PhyxWrapper.js#L147-L149

These should really be settable when creating the PhyxWrapper. Changing the JSON context can be useful when editing the context, when you'd like the emitted JSON-LD file to refer to a local file rather than the official release online.

Changing the base URI is particularly useful because Protege can't open JSON-LD files that *don't* have a base URI (i.e. those that have IDs in the form `#phyloref1`), so exports intended for Protege should have a dummy base URI set, while exports intended for JPhyloRef don't need them.

**Comment by hlapp** [comment]
WIP or forgot to assign?

**Comment by gaurav** [comment]
We don't need to make the JSON-LD context editable, since an existing `@context` in the wrapped Phyx file is never overwritten. One can therefore be set before or after calling `asOWLOntology()`. I've therefore modified this issue title to apply only to the baseURI.
