### ISSUE TITLE
Standardize nomenclatural codes with TCAN

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#41]
We use `tn:nomenclaturalCode` to store the nomenclatural code for a particular name, but instead of using the codes from the TaxonName ontology (e.g. `tn:ICZN`), we use use codes from the NOMEN ontology. The TCAN ontology provides relationships between those two sets of nomenclatural codes, and we should look into how to use these different sets of nomenclatural codes correctly.

**Comment by hlapp** [comment]
Can you give an example in TTL? The two are different animals. `tn:` code terms are individuals, whereas those in `NOMEN` are classes. Are you saying you have been punting the classes to individuals?

**Comment by gaurav** [comment]
Right now, when stored in a Phyx file, TUs with taxon names look like this:

```
{
  "@type": "http://rs.tdwg.org/ontology/voc/TaxonConcept#TaxonConcept",
  "hasName": {
    "@type": "http://rs.tdwg.org/ontology/voc/TaxonName#TaxonName",
    "nomenclaturalCode": "http://purl.obolibrary.org/obo/NOMEN_0000107",
    "label": "Alligator mississippiensis",
    "nameComplete": "Alligator mississippiensis",
    "genusPart": "Alligator",
    "specificEpithet": "mississippiensis"
   }
}
```

When converted into an ontology, I plan to represent them like this (in Manchester syntax):
```
represents_TU some ('Has Name' some (
  obo:NOMEN_0000107 and
  ('Has Scientific Name' value "Alligator mississippiensis")
)
```

This differs from the way in which you defined them back in 2018, which was:

```
represents_TU some ('Has Name' some (
  ('Nomenclatural Code' value tn:ICZN)
  and ('Has Scientific Name' value "Alligator mississippiensis")))
)
```

Is there a benefit to using `tn:ICZN` instead of `obo:NOMEN_0000107`? If not, I'll modify the Phyx format so we use tn:ICZN instead of obo:NOMEN_0000107 as a class; that way, both the Phyx and ontology representations of the nomenclatural code can use the same term.

**Comment by hlapp** [comment]
I don't think a taxonomic name is (or should be) an instance of nomenclatural code?

**Comment by hlapp** [comment]
@gaurav can we wrap this up?

**Comment by gaurav** [comment]
I think that makes sense, and we should be able to move to the `('Nomenclatural Code' value tn:ICZN)` format without too much change. I've updated that in the manuscript and I'll work on changing the code here once we're done with writing.

Note that [`obo:NOMEN_0000107`](https://www.ebi.ac.uk/ols/ontologies/nomen/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNOMEN_0000107) (ICZN name) is the class of ICZN names, not a nomenclatural code. So I think the OWL expression is correct, but there's a discrepancy in the JSON representation, which is that the field is named "nomenclaturalCode" in the JSON representation rather than adding `obo:NOMEN_0000107` to the list of types in `@type`. I think the "nomenclaturalCode" field is clearer, so let's go with that.

**Comment by hlapp** [comment]
Good point and indeed I missed that this is a class of a kind of names, not a kind of nomenclatural codes. I agree with your reasoning re: the two alternatives.

**Comment by gaurav** [comment]
As of PR #70, we now write out phyloreferences as e.g.

```
(excludes_TU some ('Has Name' some (
       ('Nomenclatural Code' value ICZN)
       and ('Name Complete' value "Caiman crocodilus"))))
and (includes_TU some ('Has Name' some (
       ('Nomenclatural Code' value ICZN)
       and ('Name Complete' value "Alligator mississippiensis"))))
```
