### ISSUE TITLE
Investigate example of a phyloref that resolves to two nodes

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#57]
Because of the way in which phyloreferences are constructed, we know that they sometimes resolve to more than one node. One example we have of this is a phyloreference adapted from [Brochu 2003](https://www.annualreviews.org/doi/abs/10.1146/annurev.earth.31.100901.141308), defined as the maximum clade including *Tomistoma schlegelii* but excluding *Gavialis gangeticus*. When resolved against the following phylogeny, both the correct node ("Brevirostres") as well as an incorrect node, which is the direct child of the correct node ("Crocodylidae"): ('Gavialis gangeticus',(('Diplocynodon ratelii',('Alligator mississippiensis','Caiman crocodilus')Alligatoridae)Alligatoroidea,('Tomistoma schlegelii',('Osteolaemus tetraspis','Crocodylus niloticus')Crocodylinae)Crocodylidae)Brevirostres)Crocodylia

This issue covers two tasks:
1. We should add a test case to record that this happens. On first glance, it might seem to make more sense to put this test in JPhyloRef rather than in Phyx.js, but this would require storing both the definition and the phylogeny in OWL, which would be hard to read. Instead, it might make sense to have a folder of phyloreferences in this repository and require users to download JPhyloRef to test them.
2. We should try to replicate this in every-topology-testing. We haven't seen it yet, but we have so far only gone up to 6 leaf nodes -- it might be that this behavior only appears with at least 7 leaf nodes. I'll attempt to generate phylogenies for n=7 and see if I can replicate this behavior there.

**Comment by hlapp** [comment]
It's worth noting that when this happens it's nothing intrinsic to the phyloreference itself, but it's a side effect of the phyloreference class definitions that are in the same ontology. So the subject is a little misleading.

**Comment by hlapp** [comment]
As I reported this is a result of the equivalentClass expressions for Crocodyloidea. We effectively assert that these different expressions (matching different possible topologies) are equivalent by asserting them as equivalent to the same class. As we know, tthe equivalency of the expressions is factually incorrect, so sometimes these are bound to have unintended side effects for reasoning with expressions that target nearby or the same MRCA nodes.

If a single phyloreference is put together into an ontology with one or more trees (such as for the most typical use case, to resolve the phyloreference), the incorrect assertion won't ever matter.

The solution to prevent the unintended side effects is to prevent the reasoner from inferring that the different class expressions are equivalent. This can be done by creating subclasses, each of which will be defined equivalent to a single class expression. This means the type inference (instance classification used to resolve to a node) will be direct only to the subclass, meaning the type inference for the phyloreference (now the superclass) will be indirect, for code for which this difference matters.

**Comment by hlapp** [comment]
We might also contemplate an "edit" version of the Clade Ontology, and a published version generated from it. The "edit" version for simplicity will enumerate the class expressions directly as equivalentClass axioms, and the published version would move each one into a generated subclass.

I'm not sure there's an easy (or even any) way to accomplish this with _robot_, so between creating a custom tool necessary for generating the published version and generating subclasses in the first place even for the "edit" version, I think I would favor the latter.

**Comment by gaurav** [comment]
We now use a subclass based approach that does not appear to be vulnerable to this issue. I will close it for now, but we can reopen it if we start seeing a single phyloreference resolving to multiple nodes again.
