### ISSUE TITLE
Add RDF properties for bibliography to JSON context

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyx.js#64]
Currently, citations are not exported to JSON-LD because we don't have RDF properties to map them to. I've added a mapping from "title" to "dc:title" (#59), but I think it would be a good idea to map all of them. We could use [FaBiO](http://www.sparontologies.net/ontologies/fabio) or [BiBo](https://www.dublincore.org/specifications/bibo/bibo/bibo.rdf.xml).

**Comment by hlapp** [comment]
Good question of which one to use. Does either of them seem easier to implement? We should keep in mind that bibliographic citations aren't among our core business by any means, so the standard we choose should arguably (1) qualify as a community standard already in current use, (2) include the properties we need, and (3) be the easiest to implement among those satisfying other criteria.

**Comment by gaurav** [comment]
In PR #66 I converted the citation into a single string and stored it as a `dc:bibliographicCitation`. This is probably as much detail as we need. Closing.
